### ISSUE TITLE
CI/CD Interoperability

### ISSUE THREAD

**Issue by jyavorska** [flemay/3musketeers#24]
Hello, I've been thinking about CI/CD container interoperability and someone recommended I should take a look at your project. I'm very glad I did because it looks like we are thinking at least in the same direction.

I wrote down some ideas at https://gitlab.com/jyavorska/opencicontainer/-/blob/master/README.md, where I'm trying to come up with a native container format (or maybe wrapper?) that can be called from any CI system.

Curious if this is something that's part of the plans for 3musketeers? Or if you've given it any thought?

**Comment by flemay** [comment]
Hi @fastloris ! Thank you for writing and I'm glad you came across this project. I've read your `README`. I didn't thought about having a unified language for pipelines like you did. It really sounds like what Microsoft is doing with its [Language Server Protocol](https://microsoft.github.io/language-server-protocol/). Interesting and if that becomes a reality, I sure will add a section in the 3 musketeers documentation! 

True that the 3 Musketeers philosophy is all about being platform (including CI/CD) agnostic. We tend to extract as much logic out of the CI/CD files as possible leaving it to only call simple commands. So the task of creating pipelines is not very hard even if there is a need to change CI/CD tool.

I don't know much about the underlying but there are some big differences between let's say GitHub Actions - _FYI can be written in YAML_ - and GoCD that may be quite hard to unify. GitHub Actions is all about user events (like PR, merge, comment, etc) and does not support (yet?) multi-stage pipeline.

**Comment by yunspace** [comment]
If I understood correctly @fastloris, you idea is to have a unified Pipeline as Code (PaC) DSL for common CI/CD vendors . I'd say this would not be part of the plan for 3M.

First of all let's start with the why. Why do we need this, does it add any value or is it abstraction of the sake of abstraction? The concept reminds me of SLF4J which became essentially a lowest common denominator facade for various logger implementations. In the rare occasion when engineers did need to change logger implementation, it was actually much easier to just do a quick IDE refactor. Just as you are better off using log4j or java.util.logs directly in the java land, the benefit of using the vendor specific Pipeline as Code syntax is that you get the best and latest features they have to offer, 

3M has zero code maintenance because it is not a code framework, but a methodology that composes 3 mature open source tools. The problem with a "unifying CI/CD DSL" is that we would have to write and maintain code, fix bugs and support the various CI/CD vendors, requiring lots of effort and minimal gains.

To Fred's point, once 3M is in place, it's not hard at all to change underlying CI/CD at all. I've personally changed the underlying pipeline of a complex AWS landing zone with 300+ account from gitlab to circleci to code build. Each time taking less than a few couples of hours to rewrite the yaml each time.
